version: '3.7'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "9080:9080"
    depends_on:
        - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/usermanagerdb
  postgres:
    image: postgres:15
    ports:
      - "35000:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: sa
      POSTGRES_USER: postgres
      POSTGRES_DB: usermanagerdb
  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.pl
      PGADMIN_DEFAULT_PASSWORD: sa
  maildev:
    image: maildev/maildev
    ports:
      - "7080:1080"
      - "8025:1025"